version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/wwwyo/skillet
